/**
 * Writes docs/configuration/rules-reference.md from the rule registry.
 * Run with `pnpm docs:rules` (from the repo root) or `pnpm --filter @gribble/core docs:rules`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { renderRulesReference } from "../src/rules/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, "../../../docs/configuration/rules-reference.md");

const frontmatter = [
	"---",
	"title: Rules reference",
	"description: Every rule Gribble knows, with options, preset defaults and fix hints.",
	"order: 32",
	"---",
	"",
	"<!-- Generated by packages/core/scripts/generate-rules-docs.ts from the rule registry. Do not edit by hand; run `pnpm docs:rules`. -->",
	"",
].join("\n");

await mkdir(dirname(target), { recursive: true });
await writeFile(target, frontmatter + renderRulesReference(), "utf8");
console.log(`wrote ${target}`);
